---
version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 15
  complex-logic:
    config:
      threshold: 15
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

engines:
  duplication:
    enabled: false
    config:
      languages:
        php:
          mass_threshold: 30
  phpcodesniffer:
    enabled: true
    config:
      standard: PSR2
    checks:
      PSR1 Files SideEffects FoundWithSymbols:
        enabled: false
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
      Squiz Classes ValidClassName NotCamelCaps:
        enabled: false

ratings:
  paths:
  - "**.php"

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "bin/"
- "build/"
- "data/"
- "docs/"
- "docs-api/"
- "language_files/"
- "lib/"
- "sef/"
- "tests/"
- "tmpl/"
