---
engines:
  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 30
  phpcodesniffer:
    enabled: true
    config:
      standard: PSR2

ratings:
  paths:
  - "**.php"

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "bin/"
- "build/"
- "docs/"
- "docs-api/"
- "language_files/"
- "lib/"
- "sef/"
- "tests/"
- "tmpl/"
