env:
  global:
    - CC_TEST_REPORTER_ID=e39b0f2af75dee543f855fa2ae6c394324d8b4965bee3a3cbd16b970e82b9bce
    - SAUCE_USERNAME=andrewscaya
    - secure: "Cwt3tdw/XN4MX/rLxCh23Af6y6GOKccX/YTPCQUAJDkKvUDqPtM/Q0PnCQwHdOfhmliFsP9QVZzrv3cZrpggNrjU5cctc+w9GsdMogZlEULaV3sa4DgXHjfrTniguOh2YsZQ3tcTQkL/jH3mJ6FiY+8zZOGJvMEydyFp5u06khW/ahmot6EVkXt6+4dswtfckTaQZiXBdOdjyZ9lMbnjEpeLp7Ed0FqQDdq9GZK0M9weurEHZwLhClXzyMhHMA4GolvYCFR9+a1WBU3T/c3GJjMfVLjqvW3l5MzI1/ShFeC8/mXaaWfzNobo+x6Iv3CNUB657dRBxFr2PFvIx8GQYZXG1q7WBUrONoXZFUqEdUYHMTly/vGYkiMXfXYJAHpAuRmEHTyprYFDc7TtnPGC3bq5eqmUwZlE3Sjm0HnDQWhwpzVr0yTqccr3cXPNBrK9xLMTLo0sbGHRMvJLt7LltNd1dkuRNoo5sPedYK46pZQLaJ5sKWCHMNBBnVVHXJzjdaoRdFk2NY2Y9E8PMiqRl68kHl2hs7pSUu+QhrC0bPLGcf8cVxko/foPAbXDYQalG+T1zsbrPHhb5ZvE8Un3IZF6Gpl1QeYqbD0HWbm/chHy+0oXiIvRAESxoQtv505if1u8NszHYZVL0+Cj/dkKunwhZoIhr+DHsGyAsfE8RnU="
    - secure: "fatMNhRKgFgwcE0AY1kcuL/hC7698iOta96kotcpBT4kCrIJ0HjlhVWzh94JzSYl0MaiSU0hgi/KG1Goo/8byEbkB3TYrw/gasJLontbl6aCVPNi/HRS4uD2kvB6NzqNzkvX9zd4L/MjZzOJc0CGR/EbO/gVhXYqodL8Qbj5Kdwlodx7Aa4CIC0vF+WiwArQWqIFWPoRG81dgxd0Ze95fOQwLYfSuwmm1IWor42oZLR4UnAEtIDDcuCVKEeADgPWsTIUZP+05KhiMhE8sGV2kolp4FbG8yqFsGe06DfGTnCujFdPZINobEip7HmKhZQWmgC9/9QJLW1G+jcA2cwugk4/1hz0eiuFbVZcElY3yISwNOv3UrQX49FOZ83AiueqwODfhdaGBgVXStSj0f2lKPixRD5M/0dovHT0qDKB0C/OnBYDXtUW84U+dBi2LlQKRFZn5XJ2uDYGWnTsMIAbtttxdmMDg/9GXFWY+/5PXzTaD38+V+C1BGxI4/xfTk8Pm8sLJef08vm7apPv/x4k3YaBxIxVbXfg9UgN2mYcaQxJBMCOHxiRr77gHqmPmEAtRCVFWJ+t/e8UcCRReD2gYZ/WmTRnTz5YmaaaySA5yr+KpwRL/UczrY4R/0KxJnOONiBl3z6UM0f/ysufaAE7bAvr07YEm3IrYVUAsVHV0Ak="

sudo: false

language: php

rvm:
  - 2.2.0

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

services:
  - mysql

addons:
  sauce_connect: true

branches:
  except:
    - 1.8.9
    - 1.8.8
    - 1.8.7
    - develop

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - COMPOSER_PROCESS_TIMEOUT=1200
        - TEST_CHECK=true
        - CS_CHECK=true
        - CC_CHECK=true
    - php: 5.6
      env:
        - COMPOSER_PROCESS_TIMEOUT=1200
        - TEST_CHECK_COVER=true
        - CS_CHECK=true
        - CC_CHECK=true
    - php: 7
      env:
        - TEST_CHECK=false
        - CS_CHECK=true
        - CC_CHECK=true
    - php: hhvm
      env:
        - TEST_CHECK=false
        - CS_CHECK=true
        - CC_CHECK=false
  allow_failures:
    - php: hhvm

before_install:
  - travis_retry composer self-update
  - if [[ $TEST_CHECK_54 == 'true' ]]; then rm $TRAVIS_BUILD_DIR/composer.json && mv $TRAVIS_BUILD_DIR/composer.php54.json $TRAVIS_BUILD_DIR/composer.json ; fi
  - if [[ -z "$TEST_CHECK_COVER" ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
    
install:
  - travis_retry composer install --no-interaction

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - if [[ $CC_CHECK == 'true' ]]; then $TRAVIS_BUILD_DIR/bin/selenium-setup.sh ; fi
  - if [[ $CC_CHECK == 'true' ]]; then npm install -g se-interpreter ; fi

script:
  - if [[ $CC_CHECK == 'true' ]]; then se-interpreter tests/selenium/se-interpreter_config.json ; fi
  - if [[ $TEST_CHECK == 'true' || $TEST_CHECK_54 == 'true' ]]; then composer test ; fi
  - if [[ $TEST_CHECK_COVER == 'true' ]]; then composer test-cover ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs ; fi

after_script:
  - if [[ $TEST_CHECK_COVER == 'true' ]]; then mv build/logs/clover.xml clover.xml ; fi
  - if [[ $TEST_CHECK_COVER == 'true' ]]; then ./cc-test-reporter after-build --coverage-input-type clover --id 12345 --exit-code $TRAVIS_TEST_RESULT ; fi

after_success:
  - if [[ $TEST_CHECK_COVER == 'true' ]]; then composer test-report ; fi